apiVersion: v1
kind: Service
metadata:
  name     : log-zookeeper
  namespace: log
  labels:
    app: "zookeeper"
spec:
  ports:
  - port: 2181
    name: client
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: "zookeeper"

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name     : log-zookeeper
  namespace: log
  labels:
    app: "zookeeper"
spec:
  serviceName: log-zookeeper
  replicas: 3
  template:
    metadata:
      labels:
        app: "zookeeper"
    spec:
      imagePullSecrets:
      - name: regsecret
      nodeSelector:
        nodezone: b
      containers:
      - name : k8szk
        image: "registry-vpc.cn-hangzhou.aliyuncs.com/medlinker/k8szk:v3"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        env:
        - name : ZK_REPLICAS
          value: "3"
        - name : ZK_HEAP_SIZE
          value: "1G"
        - name : ZK_TICK_TIME
          value: "2000"
        - name : ZK_INIT_LIMIT
          value: "10"
        - name : ZK_SYNC_LIMIT
          value: "5"
        - name : ZK_MAX_CLIENT_CNXNS
          value: "60"
        - name: ZK_SNAP_RETAIN_COUNT
          value: "3"
        - name: ZK_PURGE_INTERVAL
          value: "1"
        - name: ZK_LOG_LEVEL
          value: INFO
        - name: ZK_CLIENT_PORT
          value: "2181"
        - name: ZK_SERVER_PORT
          value: "2888"
        - name: ZK_ELECTION_PORT
          value: "3888"
        command:
        - sh
        - -c
        - zkGenConfig.sh && exec zkServer.sh start-foreground
        readinessProbe:
          exec:
            command:
            - "zkOk.sh"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - "zkOk.sh"
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/zookeeper
      securityContext:
        runAsUser: 1000
        fsGroup: 1000

  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: alicloud-disk-common-hangzhou-b
      resources:
        requests:
          storage: 20Gi



